(function () {
  "use strict";
  var FLAG_CITIES = {
    kr: { ko: ["서울", "부산", "인천", "대구"], en: ["Seoul", "Busan", "Incheon", "Daegu"] },
    jp: { ko: ["도쿄", "오사카", "요코하마", "나고야"], en: ["Tokyo", "Osaka", "Yokohama", "Nagoya"] },
    cn: { ko: ["베이징", "상하이", "광저우", "선전"], en: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen"] },
    us: { ko: ["워싱턴 D.C.", "뉴욕", "로스앤젤레스", "시카고"], en: ["Washington, D.C.", "New York", "Los Angeles", "Chicago"] },
    gb: { ko: ["런던", "맨체스터", "버밍엄", "에든버러"], en: ["London", "Manchester", "Birmingham", "Edinburgh"] },
    fr: { ko: ["파리", "리옹", "마르세유", "툴루즈"], en: ["Paris", "Lyon", "Marseille", "Toulouse"] },
    de: { ko: ["베를린", "뮌헨", "함부르크", "프랑크푸르트"], en: ["Berlin", "Munich", "Hamburg", "Frankfurt"] },
    it: { ko: ["로마", "밀라노", "나폴리", "토리노"], en: ["Rome", "Milan", "Naples", "Turin"] },
    es: { ko: ["마드리드", "바르셀로나", "발렌시아", "세비야"], en: ["Madrid", "Barcelona", "Valencia", "Seville"] },
    ca: { ko: ["오타와", "토론토", "밴쿠버", "몬트리올"], en: ["Ottawa", "Toronto", "Vancouver", "Montreal"] },
    au: { ko: ["캔버라", "시드니", "멜버른", "브리즈번"], en: ["Canberra", "Sydney", "Melbourne", "Brisbane"] },
    br: { ko: ["브라질리아", "상파울루", "리우데자네이루", "살바도르"], en: ["Brasília", "São Paulo", "Rio de Janeiro", "Salvador"] },
    in: { ko: ["뉴델리", "뭄바이", "벵갈루루", "첸나이"], en: ["New Delhi", "Mumbai", "Bengaluru", "Chennai"] },
    ru: { ko: ["모스크바", "상트페테르부르크", "노보시비르스크", "예카테린부르크"], en: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg"] },
    mx: { ko: ["멕시코시티", "과달라하라", "몬테레이", "푸에블라"], en: ["Mexico City", "Guadalajara", "Monterrey", "Puebla"] },
    ar: { ko: ["부에노스아이레스", "코르도바", "로사리오", "멘도사"], en: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"] },
    tr: { ko: ["앙카라", "이스탄불", "이즈미르", "부르사"], en: ["Ankara", "Istanbul", "İzmir", "Bursa"] },
    sa: { ko: ["리야드", "제다", "메카", "담맘"], en: ["Riyadh", "Jeddah", "Mecca", "Dammam"] },
    eg: { ko: ["카이로", "알렉산드리아", "기자", "룩소르"], en: ["Cairo", "Alexandria", "Giza", "Luxor"] },
    za: { ko: ["프리토리아", "요하네스버그", "케이프타운", "더반"], en: ["Pretoria", "Johannesburg", "Cape Town", "Durban"] },
    nl: { ko: ["암스테르담", "로테르담", "헤이그", "위트레흐트"], en: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"] },
    se: { ko: ["스톡홀름", "예테보리", "말뫼", "웁살라"], en: ["Stockholm", "Gothenburg", "Malmö", "Uppsala"] },
    ch: { ko: ["베른", "취리히", "제네바", "바젤"], en: ["Bern", "Zurich", "Geneva", "Basel"] },
    sg: { ko: ["싱가포르", "주롱", "우들랜즈", "탬파인스"], en: ["Singapore", "Jurong", "Woodlands", "Tampines"] },
    th: { ko: ["방콕", "치앙마이", "파타야", "푸켓"], en: ["Bangkok", "Chiang Mai", "Pattaya", "Phuket"] },
    vn: { ko: ["하노이", "호치민", "다낭", "하이퐁"], en: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hai Phong"] },
    ph: { ko: ["마닐라", "세부", "다바오", "케손시티"], en: ["Manila", "Cebu", "Davao", "Quezon City"] },
    id: { ko: ["자카르타", "수라바야", "반둥", "메단"], en: ["Jakarta", "Surabaya", "Bandung", "Medan"] },
    my: { ko: ["쿠알라룸푸르", "조호르바루", "페낭", "이포"], en: ["Kuala Lumpur", "Johor Bahru", "Penang", "Ipoh"] },
    nz: { ko: ["웰링턴", "오클랜드", "크라이스트처치", "해밀턴"], en: ["Wellington", "Auckland", "Christchurch", "Hamilton"] },
    pt: { ko: ["리스본", "포르투", "브라가", "파로"], en: ["Lisbon", "Porto", "Braga", "Faro"] },
    gr: { ko: ["아테네", "테살로니키", "파트라", "이라클리온"], en: ["Athens", "Thessaloniki", "Patras", "Heraklion"] },
    pl: { ko: ["바르샤바", "크라쿠프", "브로츠와프", "그단스크"], en: ["Warsaw", "Kraków", "Wrocław", "Gdańsk"] },
    ie: { ko: ["더블린", "코크", "골웨이", "리머릭"], en: ["Dublin", "Cork", "Galway", "Limerick"] },
    be: { ko: ["브뤼셀", "안트베르펜", "헨트", "리에주"], en: ["Brussels", "Antwerp", "Ghent", "Liège"] },
    no: { ko: ["오슬로", "베르겐", "트론헤임", "스타방에르"], en: ["Oslo", "Bergen", "Trondheim", "Stavanger"] },
    dk: { ko: ["코펜하겐", "오르후스", "오덴세", "올보르"], en: ["Copenhagen", "Aarhus", "Odense", "Aalborg"] },
    fi: { ko: ["헬싱키", "탐페레", "투르쿠", "오울루"], en: ["Helsinki", "Tampere", "Turku", "Oulu"] },
    ua: { ko: ["키이우", "하르키우", "오데사", "리비우"], en: ["Kyiv", "Kharkiv", "Odesa", "Lviv"] },
    il: { ko: ["예루살렘", "텔아비브", "하이파", "베에르셰바"], en: ["Jerusalem", "Tel Aviv", "Haifa", "Beersheba"] },
    ae: { ko: ["아부다비", "두바이", "샤르자", "아지만"], en: ["Abu Dhabi", "Dubai", "Sharjah", "Ajman"] },
    at: { ko: ["빈", "그라츠", "잘츠부르크", "인스부르크"], en: ["Vienna", "Graz", "Salzburg", "Innsbruck"] },
    cz: { ko: ["프라하", "브르노", "오스트라바", "플젠"], en: ["Prague", "Brno", "Ostrava", "Plzeň"] },
    hu: { ko: ["부다페스트", "데브레첸", "세게드", "미슈콜츠"], en: ["Budapest", "Debrecen", "Szeged", "Miskolc"] },
    cl: { ko: ["산티아고", "발파라이소", "콘셉시온", "안토파가스타"], en: ["Santiago", "Valparaíso", "Concepción", "Antofagasta"] },
    co: { ko: ["보고타", "메데인", "칼리", "바랑키야"], en: ["Bogotá", "Medellín", "Cali", "Barranquilla"] },
    pe: { ko: ["리마", "아레키파", "쿠스코", "트루히요"], en: ["Lima", "Arequipa", "Cusco", "Trujillo"] },
    ng: { ko: ["아부자", "라고스", "카노", "이바단"], en: ["Abuja", "Lagos", "Kano", "Ibadan"] },
    ke: { ko: ["나이로비", "몸바사", "키수무", "나쿠루"], en: ["Nairobi", "Mombasa", "Kisumu", "Nakuru"] },
    ir: { ko: ["테헤란", "마슈하드", "이스파한", "타브리즈"], en: ["Tehran", "Mashhad", "Isfahan", "Tabriz"] },
    ro: { ko: ["부쿠레슈티", "클루지나포카", "티미쇼아라", "이아시"], en: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași"] },
    bg: { ko: ["소피아", "플로브디프", "바르나", "부르가스"], en: ["Sofia", "Plovdiv", "Varna", "Burgas"] },
    hr: { ko: ["자그레브", "스플리트", "리예카", "오시예크"], en: ["Zagreb", "Split", "Rijeka", "Osijek"] },
    rs: { ko: ["베오그라드", "노비사드", "니시", "크라구예바츠"], en: ["Belgrade", "Novi Sad", "Niš", "Kragujevac"] },
    sk: { ko: ["브라티슬라바", "코시체", "프레쇼프", "질리나"], en: ["Bratislava", "Košice", "Prešov", "Žilina"] },
    si: { ko: ["류블랴나", "마리보르", "첼레", "크란"], en: ["Ljubljana", "Maribor", "Celje", "Kranj"] },
    ee: { ko: ["탈린", "타르투", "나르바", "파르누"], en: ["Tallinn", "Tartu", "Narva", "Pärnu"] },
    lv: { ko: ["리가", "다우가프필스", "리파야", "옐가바"], en: ["Riga", "Daugavpils", "Liepāja", "Jelgava"] },
    lt: { ko: ["빌뉴스", "카우나스", "클라이페다", "샤울레이"], en: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai"] },
    is: { ko: ["레이캬비크", "아쿠레이리", "코파보귀르", "하프나르피외르뒤르"], en: ["Reykjavík", "Akureyri", "Kópavogur", "Hafnarfjörður"] },
    lu: { ko: ["룩셈부르크", "에슈쉬르알제트", "디페르당주", "뒤델랑주"], en: ["Luxembourg", "Esch-sur-Alzette", "Differdange", "Dudelange"] },
    mt: { ko: ["발레타", "비르키르카라", "모스타", "슬리마"], en: ["Valletta", "Birkirkara", "Mosta", "Sliema"] },
    cy: { ko: ["니코시아", "리마솔", "라르나카", "파포스"], en: ["Nicosia", "Limassol", "Larnaca", "Paphos"] },
    by: { ko: ["민스크", "호멜", "모길료프", "비텝스크"], en: ["Minsk", "Gomel", "Mogilev", "Vitebsk"] },
    md: { ko: ["키시너우", "티라스폴", "발티", "벤데르"], en: ["Chișinău", "Tiraspol", "Bălți", "Bender"] },
    mk: { ko: ["스코페", "비톨라", "쿠마노보", "프리레프"], en: ["Skopje", "Bitola", "Kumanovo", "Prilep"] },
    al: { ko: ["티라나", "두러스", "블로러", "슈코더르"], en: ["Tirana", "Durrës", "Vlorë", "Shkodër"] },
    ba: { ko: ["사라예보", "바냐루카", "투즐라", "모스타르"], en: ["Sarajevo", "Banja Luka", "Tuzla", "Mostar"] },
    me: { ko: ["포드고리차", "니크시치", "바르", "부드바"], en: ["Podgorica", "Nikšić", "Bar", "Budva"] },
    ge: { ko: ["트빌리시", "바투미", "쿠타이시", "루스타비"], en: ["Tbilisi", "Batumi", "Kutaisi", "Rustavi"] },
    am: { ko: ["예레반", "귬리", "바나조르", "바가르샤파트"], en: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat"] },
    az: { ko: ["바쿠", "간자", "숨가이트", "랑카란"], en: ["Baku", "Ganja", "Sumqayit", "Lankaran"] },
    kz: { ko: ["아스타나", "알마티", "쉼켄트", "카라간다"], en: ["Astana", "Almaty", "Shymkent", "Karaganda"] },
    uz: { ko: ["타슈켄트", "사마르칸트", "나망간", "안디잔"], en: ["Tashkent", "Samarkand", "Namangan", "Andijan"] },
    qa: { ko: ["도하", "알와크라", "알코르", "알라이얀"], en: ["Doha", "Al Wakrah", "Al Khor", "Al Rayyan"] },
    kw: { ko: ["쿠웨이트시티", "알아흐마디", "하왈리", "살미야"], en: ["Kuwait City", "Al Ahmadi", "Hawalli", "Salmiya"] },
    iq: { ko: ["바그다드", "바스라", "모술", "에르빌"], en: ["Baghdad", "Basra", "Mosul", "Erbil"] },
    sy: { ko: ["다마스쿠스", "알레포", "홈스", "라타키아"], en: ["Damascus", "Aleppo", "Homs", "Latakia"] },
    jo: { ko: ["암만", "자르카", "이르비드", "아카바"], en: ["Amman", "Zarqa", "Irbid", "Aqaba"] },
    lb: { ko: ["베이루트", "트리폴리", "시돈", "티레"], en: ["Beirut", "Tripoli", "Sidon", "Tyre"] },
    om: { ko: ["무스카트", "살랄라", "소하르", "니즈와"], en: ["Muscat", "Salalah", "Sohar", "Nizwa"] },
    bh: { ko: ["마나마", "리파", "무하라크", "이사타운"], en: ["Manama", "Riffa", "Muharraq", "Isa Town"] },
    ye: { ko: ["사나", "아덴", "타이지", "호데이다"], en: ["Sana'a", "Aden", "Taiz", "Al Hudaydah"] },
    pk: { ko: ["이슬라마바드", "카라치", "라호르", "파이살라바드"], en: ["Islamabad", "Karachi", "Lahore", "Faisalabad"] },
    bd: { ko: ["다카", "치타공", "쿨나", "라지샤히"], en: ["Dhaka", "Chittagong", "Khulna", "Rajshahi"] },
    lk: { ko: ["스리자야와르데네푸라코테", "콜롬보", "캔디", "갈"], en: ["Sri Jayawardenepura Kotte", "Colombo", "Kandy", "Galle"] },
    np: { ko: ["카트만두", "포카라", "랄릿푸르", "비라트나가르"], en: ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar"] },
    mm: { ko: ["네피도", "양곤", "만달레이", "마울라먀인"], en: ["Naypyidaw", "Yangon", "Mandalay", "Mawlamyine"] },
    kh: { ko: ["프놈펜", "시엠립", "바탐방", "시아누크빌"], en: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"] },
    la: { ko: ["비엔티안", "루앙프라방", "파크세", "사반나케트"], en: ["Vientiane", "Luang Prabang", "Pakse", "Savannakhet"] },
    mn: { ko: ["울란바토르", "에르데네트", "다르한", "초이발산"], en: ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan"] },
    af: { ko: ["카불", "칸다하르", "헤라트", "마자르이샤리프"], en: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif"] },
    kp: { ko: ["평양", "함흥", "청진", "원산"], en: ["Pyongyang", "Hamhung", "Chongjin", "Wonsan"] },
    tw: { ko: ["타이베이", "가오슝", "타이중", "타이난"], en: ["Taipei", "Kaohsiung", "Taichung", "Tainan"] },
    hk: { ko: ["홍콩", "가우룽", "신제", "침사추이"], en: ["Hong Kong", "Kowloon", "New Territories", "Tsim Sha Tsui"] },
    ve: { ko: ["카라카스", "마라카이보", "발렌시아", "바라키스메토"], en: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto"] },
    cu: { ko: ["아바나", "산티아고데쿠바", "카마구에이", "올긴"], en: ["Havana", "Santiago de Cuba", "Camagüey", "Holguín"] },
    uy: { ko: ["몬테비데오", "살토", "파이산두", "라스피에드라스"], en: ["Montevideo", "Salto", "Paysandú", "Las Piedras"] },
    py: { ko: ["아순시온", "시우다드델에스테", "엔카르나시온", "페드로후안카바예로"], en: ["Asunción", "Ciudad del Este", "Encarnación", "Pedro Juan Caballero"] },
    bo: { ko: ["수크레", "라파스", "산타크루스", "코차밤바"], en: ["Sucre", "La Paz", "Santa Cruz", "Cochabamba"] },
    ec: { ko: ["키토", "과야킬", "쿠엥카", "만타"], en: ["Quito", "Guayaquil", "Cuenca", "Manta"] },
    cr: { ko: ["산호세", "알라후엘라", "리몬", "에레디아"], en: ["San José", "Alajuela", "Limón", "Heredia"] },
    pa: { ko: ["파나마시티", "콜론", "다비드", "산티아고"], en: ["Panama City", "Colón", "David", "Santiago"] },
    gt: { ko: ["과테말라시티", "케살테낭고", "에스퀸틀라", "믹스코"], en: ["Guatemala City", "Quetzaltenango", "Escuintla", "Mixco"] },
    do: { ko: ["산토도밍고", "산티아고데로스카바예로스", "라로마나", "푸에르토플라타"], en: ["Santo Domingo", "Santiago de los Caballeros", "La Romana", "Puerto Plata"] },
    jm: { ko: ["킹스턴", "몬테고베이", "스패니시타운", "만데빌"], en: ["Kingston", "Montego Bay", "Spanish Town", "Mandeville"] },
    hn: { ko: ["테구시갈파", "산페드로술라", "라세이바", "촐루테카"], en: ["Tegucigalpa", "San Pedro Sula", "La Ceiba", "Choluteca"] },
    ni: { ko: ["마나과", "레온", "그라나다", "마사야"], en: ["Managua", "León", "Granada", "Masaya"] },
    sv: { ko: ["산살바도르", "산타아나", "산미겔", "소야팡고"], en: ["San Salvador", "Santa Ana", "San Miguel", "Soyapango"] },
    ht: { ko: ["포르토프랭스", "카프아이티앵", "고나이브", "레카예"], en: ["Port-au-Prince", "Cap-Haïtien", "Gonaïves", "Les Cayes"] },
    ma: { ko: ["라바트", "카사블랑카", "마라케시", "페스"], en: ["Rabat", "Casablanca", "Marrakesh", "Fez"] },
    dz: { ko: ["알제", "오랑", "콘스탄틴", "안나바"], en: ["Algiers", "Oran", "Constantine", "Annaba"] },
    tn: { ko: ["튀니스", "스팍스", "수스", "카이르완"], en: ["Tunis", "Sfax", "Sousse", "Kairouan"] },
    ly: { ko: ["트리폴리", "벵가지", "미스라타", "사브라타"], en: ["Tripoli", "Benghazi", "Misrata", "Sabratha"] },
    et: { ko: ["아디스아바바", "디레다와", "메켈레", "곤다르"], en: ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar"] },
    gh: { ko: ["아크라", "쿠마시", "타말레", "세콘디타코라디"], en: ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi"] },
    sn: { ko: ["다카르", "티에스", "생루이", "카올라크"], en: ["Dakar", "Thiès", "Saint-Louis", "Kaolack"] },
    ci: { ko: ["야무수크로", "아비장", "부아케", "산페드로"], en: ["Yamoussoukro", "Abidjan", "Bouaké", "San-Pédro"] },
    cm: { ko: ["야운데", "두알라", "가루아", "바멘다"], en: ["Yaoundé", "Douala", "Garoua", "Bamenda"] },
    cd: { ko: ["킨샤사", "루붐바시", "음부지마이", "키산가니"], en: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kisangani"] },
    cg: { ko: ["브라자빌", "포인트누아르", "돌리지", "은카이"], en: ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi"] },
    tz: { ko: ["도도마", "다르에스살람", "므완자", "아루샤"], en: ["Dodoma", "Dar es Salaam", "Mwanza", "Arusha"] },
    ug: { ko: ["캄팔라", "엔테베", "진자", "구루"], en: ["Kampala", "Entebbe", "Jinja", "Gulu"] },
    zw: { ko: ["하라레", "불라와요", "치퉁위자", "무타레"], en: ["Harare", "Bulawayo", "Chitungwiza", "Mutare"] },
    ao: { ko: ["루안다", "우암보", "로비토", "벵겔라"], en: ["Luanda", "Huambo", "Lobito", "Benguela"] },
    mz: { ko: ["마푸토", "베이라", "남풀라", "마톨라"], en: ["Maputo", "Beira", "Nampula", "Matola"] },
    zm: { ko: ["루사카", "키트웨", "은돌라", "리빙스턴"], en: ["Lusaka", "Kitwe", "Ndola", "Livingstone"] },
    bw: { ko: ["가보로네", "프란시스타운", "몰레폴로레", "마운"], en: ["Gaborone", "Francistown", "Molepolole", "Maun"] },
    na: { ko: ["빈트후크", "월비스베이", "룬두", "스와콥문트"], en: ["Windhoek", "Walvis Bay", "Rundu", "Swakopmund"] },
    rw: { ko: ["키갈리", "부타레", "기세니", "루헹게리"], en: ["Kigali", "Butare", "Gisenyi", "Ruhengeri"] },
    sd: { ko: ["하르툼", "옴두르만", "포트수단", "니아라"], en: ["Khartoum", "Omdurman", "Port Sudan", "Nyala"] },
    ss: { ko: ["주바", "와우", "말라칼", "예이"], en: ["Juba", "Wau", "Malakal", "Yei"] },
    mg: { ko: ["안타나나리보", "투아마시나", "안시라나나", "피아나란초아"], en: ["Antananarivo", "Toamasina", "Antsiranana", "Fianarantsoa"] },
    mu: { ko: ["포트루이스", "보바생", "퀴레피프", "바코아"], en: ["Port Louis", "Beau Bassin", "Curepipe", "Vacoas"] },
    fj: { ko: ["수바", "라우토카", "난디", "라바사"], en: ["Suva", "Lautoka", "Nadi", "Labasa"] },
    pg: { ko: ["포트모르즈비", "라에", "마당", "마운트하겐"], en: ["Port Moresby", "Lae", "Madang", "Mount Hagen"] },
    bn: { ko: ["반다르스리브가완", "쿠알라벨라이트", "세리아", "투통"], en: ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong"] },
    kg: { ko: ["비슈케크", "오시", "잘랄아바트", "카라콜"], en: ["Bishkek", "Osh", "Jalal-Abad", "Karakol"] },
    tj: { ko: ["두샨베", "후잔트", "쿨롭", "보흐타르"], en: ["Dushanbe", "Khujand", "Kulob", "Bokhtar"] },
    tm: { ko: ["아슈하바트", "투르크멘바시", "마리", "다쇼구즈"], en: ["Ashgabat", "Türkmenbaşy", "Mary", "Daşoguz"] },
    ad: { ko: ["안도라라베야", "에스칼데스엥고르다니", "엔캄프", "산줄리아데로리아"], en: ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria"] },
    ag: { ko: ["세인트존스", "올세인트스", "리버티", "코드링턴"], en: ["Saint John's", "All Saints", "Liberta", "Codrington"] },
    bf: { ko: ["와가두구", "보보디울라소", "쿨두구", "반포라"], en: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Banfora"] },
    bi: { ko: ["기테가", "부줌부라", "응고지", "루몽게"], en: ["Gitega", "Bujumbura", "Ngozi", "Rumonge"] },
    bj: { ko: ["포르토노보", "코토누", "파라쿠", "주구"], en: ["Porto-Novo", "Cotonou", "Parakou", "Djougou"] },
    bs: { ko: ["나소", "프리포트", "웨스트엔드", "마시하버"], en: ["Nassau", "Freeport", "West End", "Marsh Harbour"] },
    bt: { ko: ["팀푸", "파로", "푼촐링", "왕두에포드랑"], en: ["Thimphu", "Paro", "Phuentsholing", "Wangdue Phodrang"] },
    bz: { ko: ["벨모판", "벨리즈시티", "산이그나시오", "오렌지워크"], en: ["Belmopan", "Belize City", "San Ignacio", "Orange Walk"] },
    cf: { ko: ["방기", "빔보", "베르베라티", "카르노"], en: ["Bangui", "Bimbo", "Berbérati", "Carnot"] },
    cv: { ko: ["프라이아", "민델로", "산타마리아", "아소마다"], en: ["Praia", "Mindelo", "Santa Maria", "Assomada"] },
    dj: { ko: ["지부티", "알리사비에", "타주라", "오보크"], en: ["Djibouti", "Ali Sabieh", "Tadjoura", "Obock"] },
    dm: { ko: ["로조", "포츠머스", "마리고", "케인필드"], en: ["Roseau", "Portsmouth", "Marigot", "Canefield"] },
    er: { ko: ["아스마라", "케레렌", "마사와", "아사브"], en: ["Asmara", "Keren", "Massawa", "Assab"] },
    fm: { ko: ["팔리키르", "콜로니아", "웨노", "톨"], en: ["Palikir", "Colonia", "Weno", "Tol"] },
    ga: { ko: ["리브르빌", "포르장틸", "프랑스빌", "오옘"], en: ["Libreville", "Port-Gentil", "Franceville", "Oyem"] },
    gd: { ko: ["세인트조지스", "구야브", "그렌빌", "빅토리아"], en: ["Saint George's", "Gouyave", "Grenville", "Victoria"] },
    gm: { ko: ["반줄", "세레쿤다", "브리카마", "바카우"], en: ["Banjul", "Serekunda", "Brikama", "Bakau"] },
    gn: { ko: ["코나크리", "은제레코레", "캉칸", "킨디아"], en: ["Conakry", "Nzérékoré", "Kankan", "Kindia"] },
    gq: { ko: ["말라보", "바타", "에비베이인", "몽고모"], en: ["Malabo", "Bata", "Ebebiyín", "Mongomo"] },
    gw: { ko: ["비사우", "바파타", "가부", "카셰우"], en: ["Bissau", "Bafatá", "Gabú", "Cacheu"] },
    gy: { ko: ["조지타운", "린덴", "뉴암스테르담", "바티카"], en: ["Georgetown", "Linden", "New Amsterdam", "Bartica"] },
    ki: { ko: ["타라와", "베티오", "바이리키", "테마쿠"], en: ["Tarawa", "Betio", "Bairiki", "Temaiku"] },
    km: { ko: ["모로니", "무차무두", "퐁고니", "돔니"], en: ["Moroni", "Mutsamudu", "Fomboni", "Domoni"] },
    kn: { ko: ["바스테르", "찰스타운", "샌디포인트", "카요네"], en: ["Basseterre", "Charlestown", "Sandy Point", "Cayon"] },
    lc: { ko: ["캐스트리스", "뷰포르", "그로스일레", "수프리에르"], en: ["Castries", "Vieux Fort", "Gros Islet", "Soufrière"] },
    li: { ko: ["바두츠", "샨", "트리젠", "발처스"], en: ["Vaduz", "Schaan", "Triesen", "Balzers"] },
    lr: { ko: ["몬로비아", "그바르가", "부카난", "카카타"], en: ["Monrovia", "Gbarnga", "Buchanan", "Kakata"] },
    ls: { ko: ["마세루", "테야테야넹", "마페텡", "헤리베"], en: ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse"] },
    mc: { ko: ["모나코", "몬테카를로", "라콩다민", "퐁비에유"], en: ["Monaco", "Monte Carlo", "La Condamine", "Fontvieille"] },
    mh: { ko: ["마주로", "에베예", "자리트", "우티릭"], en: ["Majuro", "Ebeye", "Jaluit", "Utirik"] },
    ml: { ko: ["바마코", "시카소", "세구", "몹티"], en: ["Bamako", "Sikasso", "Ségou", "Mopti"] },
    mr: { ko: ["누악쇼트", "누아디부", "로소", "카에디"], en: ["Nouakchott", "Nouadhibou", "Rosso", "Kaédi"] },
    mv: { ko: ["말레", "아두", "풀라후시", "쿨후두리"], en: ["Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi"] },
    mw: { ko: ["릴롱궤", "블랜티어", "므주주", "좀바"], en: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba"] },
    ne: { ko: ["니아메", "잔데르", "마라디", "아गा데스"], en: ["Niamey", "Zinder", "Maradi", "Agadez"] },
    nr: { ko: ["야렌", "아이워", "메넹", "부아다"], en: ["Yaren", "Aiwo", "Meneng", "Buada"] },
    pw: { ko: ["응게룰무드", "코로르", "메레케오크", "아이라이"], en: ["Ngerulmud", "Koror", "Melekeok", "Airai"] },
    sb: { ko: ["호니아라", "기조", "아우키", "키라키라"], en: ["Honiara", "Gizo", "Auki", "Kirakira"] },
    sc: { ko: ["빅토리아", "앙스로얄", "보발롱", "타카마카"], en: ["Victoria", "Anse Royale", "Beau Vallon", "Takamaka"] },
    sl: { ko: ["프리타운", "보", "케네마", "마케니"], en: ["Freetown", "Bo", "Kenema", "Makeni"] },
    sm: { ko: ["산마리노", "세라발레", "보르고마조레", "도마냐노"], en: ["San Marino", "Serravalle", "Borgo Maggiore", "Domagnano"] },
    so: { ko: ["모가디슈", "하르게이사", "보스아소", "키즈마요"], en: ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo"] },
    sr: { ko: ["파라마리보", "리에르도르프", "니외우닉커리", "모엥고"], en: ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo"] },
    st: { ko: ["상투메", "산투안토니우", "네베스", "트린다드"], en: ["São Tomé", "Santo António", "Neves", "Trindade"] },
    sz: { ko: ["음바바네", "만지니", "시테키", "늘랑가노"], en: ["Mbabane", "Manzini", "Siteki", "Nhlangano"] },
    td: { ko: ["은자메나", "문두", "사르", "아베셰"], en: ["N'Djamena", "Moundou", "Sarh", "Abéché"] },
    tg: { ko: ["로메", "소코드", "카라", "아타크파메"], en: ["Lomé", "Sokodé", "Kara", "Atakpamé"] },
    tl: { ko: ["딜리", "바우카우", "말리아나", "수아이"], en: ["Dili", "Baucau", "Maliana", "Suai"] },
    to: { ko: ["누쿠알로파", "네아푸", "파앙아이", "네이아푸외항"], en: ["Nukuʻalofa", "Neiafu", "Pangai", "Ohonua"] },
    tt: { ko: ["포트오브스페인", "산페르난도", "차과나스", "아리마"], en: ["Port of Spain", "San Fernando", "Chaguanas", "Arima"] },
    tv: { ko: ["푸나푸티", "바이아푸", "아사우", "파카시"], en: ["Funafuti", "Vaiaku", "Asau", "Fangaua"] },
    vc: { ko: ["킹스타운", "조지타운", "바루알리우", "바록홀"], en: ["Kingstown", "Georgetown", "Barrouallie", "Layou"] },
    vu: { ko: ["포트빌라", "루간빌", "이사겔", "노르수프"], en: ["Port Vila", "Luganville", "Isangel", "Norsup"] },
    ws: { ko: ["아피아", "살레로로가", "바이텔레", "팔레아시우"], en: ["Apia", "Salelologa", "Vaitele", "Faleasiu"] },
    bb: { ko: ["브리지타운", "스페이츠타운", "홀타운", "오이스틴스"], en: ["Bridgetown", "Speightstown", "Holetown", "Oistins"] },
    mo: { ko: ["마카오", "타이파", "콜로안", "콧타이"], en: ["Macao", "Taipa", "Coloane", "Cotai"] },
    pr: { ko: ["산후안", "바야몬", "캐롤라이나", "폰세"], en: ["San Juan", "Bayamón", "Carolina", "Ponce"] },
    gu: { ko: ["하갓냐", "데데도", "타무닝", "망길라오"], en: ["Hagåtña", "Dededo", "Tamuning", "Mangilao"] },
    vi: { ko: ["샬럿아말리에", "크리스천스테드", "프레데릭스테드", "크루즈베이"], en: ["Charlotte Amalie", "Christiansted", "Frederiksted", "Cruz Bay"] },
    gl: { ko: ["누크", "시시미우트", "일룰리사트", "카코르토크"], en: ["Nuuk", "Sisimiut", "Ilulissat", "Qaqortoq"] },
    fo: { ko: ["토르스하운", "클라크스비크", "푸글라피외르뒤르", "트보로이리"], en: ["Tórshavn", "Klaksvík", "Fuglafjørður", "Tvøroyri"] },
    ax: { ko: ["마리에함", "예말라", "핀스트룀", "함마르란드"], en: ["Mariehamn", "Jomala", "Finström", "Hammarland"] },
    gi: { ko: ["지브롤터", "웨스트사이드", "사우스디스트릭트", "유로포트"], en: ["Gibraltar", "Westside", "South District", "Europa Point"] },
    im: { ko: ["더글러스", "램지", "필", "캐슬타운"], en: ["Douglas", "Ramsey", "Peel", "Castletown"] },
    je: { ko: ["세인트헬리어", "세인트브렐라드", "세인트클레멘트", "그루빌"], en: ["Saint Helier", "Saint Brelade", "Saint Clement", "Gorey"] },
    gg: { ko: ["세인트피터포트", "세인트샘슨", "베일", "카텔"], en: ["Saint Peter Port", "Saint Sampson", "Vale", "Castel"] },
    bm: { ko: ["해밀턴", "세인트조지", "사우샘프턴", "워릭"], en: ["Hamilton", "St. George's", "Southampton", "Warwick"] },
    ky: { ko: ["조지타운", "웨스트베이", "보다운타운", "이스트엔드"], en: ["George Town", "West Bay", "Bodden Town", "East End"] },
    vg: { ko: ["로드타운", "스패니시타운", "더세틀먼트", "케인가든베이"], en: ["Road Town", "Spanish Town", "The Settlement", "Cane Garden Bay"] },
    tc: { ko: ["코크번타운", "프로비던시알레스", "그랜드터크", "사우스카이코스"], en: ["Cockburn Town", "Providenciales", "Grand Turk", "South Caicos"] },
    ai: { ko: ["더밸리", "샌디그라운드", "블로잉포인트", "아일랜드하버"], en: ["The Valley", "Sandy Ground", "Blowing Point", "Island Harbour"] },
    ms: { ko: ["플리머스", "브레즈비", "세일렘", "세인트피터스"], en: ["Plymouth", "Brades", "Salem", "St. Peter's"] },
    ck: { ko: ["아바루아", "아루탕가", "아티우", "마우케"], en: ["Avarua", "Arutanga", "Atiu", "Mauke"] },
    nu: { ko: ["알로피", "알로피사우스", "하쿠푸", "무타라우"], en: ["Alofi", "Alofi South", "Hakupu", "Mutalau"] },
    pf: { ko: ["파페에테", "파에아", "마히나", "우타로아"], en: ["Papeete", "Paea", "Mahina", "Uturoa"] },
    nc: { ko: ["누메아", "몽도르", "덤베아", "파이타"], en: ["Nouméa", "Mont-Dore", "Dumbéa", "Païta"] },
    aw: { ko: ["오랑예스타트", "산니콜라스", "노르드", "파라데라"], en: ["Oranjestad", "San Nicolas", "Noord", "Paradera"] },
    cw: { ko: ["빌렘스타트", "신트미힐", "반다립", "웨스트푼트"], en: ["Willemstad", "Sint Michiel", "Bandariba", "Westpunt"] },
    sx: { ko: ["필립스뷔르흐", "심슨베이", "쿨베이", "로워프린스쿼터"], en: ["Philipsburg", "Simpson Bay", "Cole Bay", "Lower Prince's Quarter"] },
    eh: { ko: ["엘아이운", "다클라", "스마라", "부즈두르"], en: ["Laayoune", "Dakhla", "Smara", "Boujdour"] },
    ps: { ko: ["라말라", "가자", "헤브론", "나블루스"], en: ["Ramallah", "Gaza", "Hebron", "Nablus"] },
    va: { ko: ["바티칸시국", "성베드로광장", "바티칸박물관", "바티칸정원"], en: ["Vatican City", "St. Peter's Square", "Vatican Museums", "Vatican Gardens"] }
  };
  window.FLAG_CITIES = FLAG_CITIES;
})();
